ERRACT.LS      Robot Name ROBOT 06-NOV-20 09:53:14  

2321" 06-NOV-20 09:49:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2322" 06-NOV-20 09:49:54 " SRVO-404 DCS Joint pos. limit(No.22:dsble J1 at EOAT chg,G1,A1) 11" " SERVO                         00110110" 
2324" 06-NOV-20 09:49:54 " SYST-045 TP enabled in AUTO mode                  " " STOP.G                        00100110" 
